apiVersion: v1
kind: PersistentVolume
metadata:
  name: "sheridanflix-storage"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "900Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/share"
    type: Directory