apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "sheridanflix"
  name: "sheridanflix-storage"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "900Gi"